// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7uVBKULT7pGtc03MKs3c2IOU-5J0lKoQ',
    appId: '1:559489862683:web:45057baf2483a46cbd7cbe',
    messagingSenderId: '559489862683',
    projectId: 'agri-shop-6c55c',
    authDomain: 'agri-shop-6c55c.firebaseapp.com',
    storageBucket: 'agri-shop-6c55c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBj2aAI-v-t77-9Gd6-8uSCCWRhFx0StnU',
    appId: '1:559489862683:android:68e99cb3d94d9d7fbd7cbe',
    messagingSenderId: '559489862683',
    projectId: 'agri-shop-6c55c',
    storageBucket: 'agri-shop-6c55c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABgGmywFoqQM8MXu5bvfzlYmxSSXqNAcE',
    appId: '1:559489862683:ios:fefa81af0244f076bd7cbe',
    messagingSenderId: '559489862683',
    projectId: 'agri-shop-6c55c',
    storageBucket: 'agri-shop-6c55c.appspot.com',
    iosBundleId: 'com.example.projectFinalYearSeller',
  );
}
